
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 1 } %>
  user: smaia
  password: smaia
  host: localhost

development:
  <<: *default
  database: edooka_development

  
test:
  <<: *default
  database: edooka_test


production:
  <<: *default
  database: edooka_production
  username: edooka
  password: <%= ENV['EDOOKA_DATABASE_PASSWORD'] %>
